# --------------------------------------------------
#  BASIC SITE INFO
# --------------------------------------------------
title: Dengqiang Jia   # Main site title (appears in browser tab & RSS)
tagline: Here is personal website of Dengqiang Jia. Powered by Jekyll, based on the Minimal Mistakes theme.  # Optional short tagline, used by some layouts
description: Two roads diverged in woods, I took the one less traveled by.  # Strongly recommended for SEO & social cards
